apiVersion: v1
kind: Service
metadata:
  labels:
    experimental.istio.io/disable-gateway-port-translation: "true"
  name: knative-local-gateway
  namespace: {{ .ControlPlane.Namespace }}
spec:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8081
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082      
  selector:
    knative: ingressgateway
  type: ClusterIP
